server:
  port: 7070


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jherson91fs/DAD-2024-1-G2-gateway-server.git # ruta del repositorio git
          searchPaths: config-data
          #username:
          #password:
          default-label: gateway-server




  security:
    user:
      name: root
      password: 123456
